version: 1
accounts:
  - name: anh
    coins:
      - 20000token
      - 10000foocoin
      - 200000000stake
  - name: house-rent-service
    coins:
      - 10000token
      - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: house-rent-service
  coins:
    - 5token
    - 100000stake
validators:
  - name: anh
    bonded: 100000000stake
